[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/artikel-islam/*"
  to = "/.netlify/functions/artikel-islam/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/artikel-islam"
  to = "/.netlify/functions/artikel-islam"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
